-- ============================================================================
-- RUN THIS SQL IN SUPABASE SQL EDITOR TO CREATE CACHING TABLES
-- ============================================================================
-- Go to: https://supabase.com/dashboard/project/YOUR_PROJECT/sql/new
-- Copy and paste this entire file, then click "Run"
-- ============================================================================

-- 1. Create incident_embeddings table for caching AI embeddings
CREATE TABLE IF NOT EXISTS incident_embeddings (
  incident_id UUID PRIMARY KEY REFERENCES incidents(id) ON DELETE CASCADE,
  embedding NUMERIC[] NOT NULL,
  model TEXT NOT NULL DEFAULT 'xenova-minilm-l6-v2',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_incident_embeddings_incident_id 
  ON incident_embeddings(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_embeddings_model 
  ON incident_embeddings(model);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_incident_embeddings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_incident_embeddings_updated_at ON incident_embeddings;
CREATE TRIGGER trigger_update_incident_embeddings_updated_at
  BEFORE UPDATE ON incident_embeddings
  FOR EACH ROW
  EXECUTE FUNCTION update_incident_embeddings_updated_at();

-- Add comments for documentation
COMMENT ON TABLE incident_embeddings IS 'Caches AI-generated embeddings to reduce processing time';
COMMENT ON COLUMN incident_embeddings.embedding IS '384-dimensional feature vector generated by local transformer model';
COMMENT ON COLUMN incident_embeddings.model IS 'Model identifier used to generate the embedding';

-- ============================================================================

-- 2. Create incident_translations table for caching Spanish to English translations
CREATE TABLE IF NOT EXISTS incident_translations (
  incident_id UUID PRIMARY KEY REFERENCES incidents(id) ON DELETE CASCADE,
  translated_summary TEXT NOT NULL,
  translated_keywords TEXT[] NOT NULL,
  source_language TEXT NOT NULL DEFAULT 'es',
  target_language TEXT NOT NULL DEFAULT 'en',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_incident_translations_incident_id 
  ON incident_translations(incident_id);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_incident_translations_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_incident_translations_updated_at ON incident_translations;
CREATE TRIGGER trigger_update_incident_translations_updated_at
  BEFORE UPDATE ON incident_translations
  FOR EACH ROW
  EXECUTE FUNCTION update_incident_translations_updated_at();

-- Add comments for documentation
COMMENT ON TABLE incident_translations IS 'Caches Spanish to English translations for incidents to avoid repeated translation processing';
COMMENT ON COLUMN incident_translations.translated_summary IS 'English translation of the incident summary';
COMMENT ON COLUMN incident_translations.translated_keywords IS 'English translations of incident keywords';

-- ============================================================================
-- VERIFICATION QUERIES (run these to confirm tables were created)
-- ============================================================================

-- Check if tables exist
SELECT 
  table_name,
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public' 
  AND table_name IN ('incident_embeddings', 'incident_translations')
ORDER BY table_name;

-- Check table structures
SELECT 
  table_name,
  column_name,
  data_type,
  is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' 
  AND table_name IN ('incident_embeddings', 'incident_translations')
ORDER BY table_name, ordinal_position;
