-- Migration: Switch from Groq 10D embeddings to local 384D embeddings
-- Run this in your Supabase SQL Editor

-- Step 1: Clear old incompatible embeddings (10D from Groq)
TRUNCATE TABLE incident_embeddings;

-- Step 2: Update the model column default to reflect new model
ALTER TABLE incident_embeddings 
  ALTER COLUMN model SET DEFAULT 'xenova-minilm-l6-v2';

-- Step 3: Add a comment to document the change
COMMENT ON TABLE incident_embeddings IS 
  'Caches AI-generated embeddings from local transformer model (Xenova/all-MiniLM-L6-v2) to reduce processing time. Embeddings are 384-dimensional vectors.';

COMMENT ON COLUMN incident_embeddings.embedding IS 
  '384-dimensional feature vector generated by MiniLM-L6-v2 (local model)';

-- Optional: If using pgvector extension, update vector dimension
-- Uncomment the line below if your embedding column uses the vector type
-- ALTER TABLE incident_embeddings ALTER COLUMN embedding TYPE vector(384);

-- Verification query
SELECT 
  'Migration completed' as status,
  COUNT(*) as total_embeddings,
  model
FROM incident_embeddings
GROUP BY model;
