-- Create incident_embeddings table for caching Groq AI embeddings
CREATE TABLE IF NOT EXISTS incident_embeddings (
  incident_id UUID PRIMARY KEY REFERENCES incidents(id) ON DELETE CASCADE,
  embedding NUMERIC[] NOT NULL,
  model TEXT NOT NULL DEFAULT 'groq-llama-3.3-70b',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_incident_embeddings_incident_id 
  ON incident_embeddings(incident_id);

-- Create index for model filtering (in case we switch models)
CREATE INDEX IF NOT EXISTS idx_incident_embeddings_model 
  ON incident_embeddings(model);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_incident_embeddings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_incident_embeddings_updated_at
  BEFORE UPDATE ON incident_embeddings
  FOR EACH ROW
  EXECUTE FUNCTION update_incident_embeddings_updated_at();

-- Add comment for documentation
COMMENT ON TABLE incident_embeddings IS 'Caches AI-generated embeddings from Groq to reduce API costs';
COMMENT ON COLUMN incident_embeddings.embedding IS '10-dimensional feature vector generated by Groq LLM';
COMMENT ON COLUMN incident_embeddings.model IS 'Model identifier used to generate the embedding';
